name: dockerhub

on:
  push:
  schedule:
    - cron: '15 21 * * 0'

env:
  IMAGE_NAME: infrabuilder/kaniko

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build and publish with apko
        uses: distroless/actions/apko-publish@main
        with:
          config: kaniko.yaml
          tag: docker.io/infrabuilder/kaniko:latest
          generic-user: ${{ vars.DOCKERHUB_USERNAME }}
          generic-pass: ${{ secrets.DOCKERHUB_TOKEN }}
